# Generated by Django 4.0.3 on 2022-07-23 18:26

import accounts.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyquota',
            name='card_type',
            field=models.IntegerField(choices=[(100, 'YELLOW'), (200, 'PINK'), (300, 'WHITE'), (400, 'BLUE')], default=accounts.constants.CardType),
        ),
    ]
