# Generated by Django 4.0.3 on 2022-07-23 18:52

from django.db import migrations, models
import supply.constants


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_alter_monthlyquota_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[(100, 'KG'), (200, 'LITRE'), (300, 'PACK')], default=supply.constants.UnitType['KG']),
        ),
    ]
