# Generated by Django 4.0.3 on 2022-07-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_token_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyquota',
            name='month',
            field=models.DateTimeField(default=None),
        ),
    ]
