# Generated by Django 4.0.3 on 2022-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_monthlyquota_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyquota',
            name='month',
            field=models.DateField(default=None),
        ),
    ]
