# Generated by Django 4.0.3 on 2022-07-24 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_alter_card_card_type'),
        ('supply', '0007_alter_monthlyquota_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidays',
            options={},
        ),
        migrations.AddField(
            model_name='holidays',
            name='current_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holidays',
            name='current_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holidays',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='holidays',
            unique_together={('shop', 'current_year', 'current_month')},
        ),
        migrations.CreateModel(
            name='PublicHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('holidays', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('current_year', models.IntegerField(default=0)),
                ('current_month', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('current_year', 'current_month')},
            },
        ),
    ]
