# Generated by Django 4.0.3 on 2022-07-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_alter_holidays_options_holidays_current_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='holidays',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='publicholidays',
            name='holidays',
            field=models.TextField(default='[]'),
        ),
    ]
