# Generated by Django 4.0.3 on 2022-07-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_member_card'),
        ('supply', '0012_alter_stock_product_alter_stock_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='RationShop',
        ),
        migrations.AddField(
            model_name='token',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='toke', to='accounts.rationshop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toke', to='accounts.card'),
        ),
    ]
