# Generated by Django 4.0.3 on 2022-07-25 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0014_alter_token_card_alter_token_number_alter_token_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='supply.product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='supply.token'),
        ),
    ]
