# Generated by Django 4.0.3 on 2022-07-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0017_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
