# Generated by Django 4.0.3 on 2022-07-22 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_admin_card_rationshop_user_mobile_otptoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='type',
            field=models.IntegerField(choices=[(100, 'LOGIN'), (200, 'VERIFY')], default=None),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=None)),
                ('gender', models.IntegerField(choices=[(100, 'MALE'), (200, 'FEMALE'), (300, 'OTHERS')], default=None)),
                ('occupation', models.CharField(default=None, max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.card')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
