# Generated by Django 4.0.3 on 2022-07-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='dob',
            field=models.DateTimeField(default=None),
        ),
    ]
