# Generated by Django 4.0.3 on 2022-07-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admin_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='dob',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
