# Generated by Django 4.0.3 on 2022-07-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_admin_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='rationshop',
            options={'verbose_name_plural': 'RationShops'},
        ),
    ]
