# Generated by Django 4.0.3 on 2022-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_admin_options_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rationshop',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
