# Generated by Django 4.0.3 on 2022-07-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_card_verified_rationshop_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
