# Generated by Django 4.0.3 on 2022-07-23 09:16

import accounts.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.IntegerField(choices=[(100, 'YELLOW'), (200, 'PINK'), (300, 'WHITE')], default=accounts.constants.CardType['WHITE']),
        ),
    ]
