# Generated by Django 4.0.3 on 2022-07-23 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_card_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='expired_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 16, 14, 30, 803621)),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
