# Generated by Django 4.0.3 on 2022-07-23 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_otptoken_expired_in_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expired_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 16, 19, 44, 806388)),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
