# Generated by Django 4.0.3 on 2022-07-23 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_otptoken_expired_in_alter_otptoken_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expired_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 18, 19, 56, 813484)),
        ),
    ]
